apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-permissions
rules:
- apiGroups: [ "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
- apiGroups: [""]
  resources: ["namespaces", "configmaps", "secrets", "services", "serviceaccounts"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-permissions
subjects:
- kind: ServiceAccount
  name: flux-applier
  apiGroup: ""
roleRef:
 kind: Role
 name: flux-permissions
 apiGroup: "rbac.authorization.k8s.io"