apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: StagedUpdateStrategy
metadata:
  name: nginx-update-strategy
spec:
  stages:
    - name: staging
      labelSelector:
        matchLabels:
          kubernetes-fleet.io/env: staging
      maxConcurrency: 1
      afterStageTasks:
        - type: TimedWait
          waitTime: 1m
        - type: Approval
    - name: canary
      labelSelector:
        matchLabels:
          kubernetes-fleet.io/env: canary
      maxConcurrency: 50%
    - name: prod
      labelSelector:
        matchLabels:
          kubernetes-fleet.io/env: prod
      maxConcurrency: 30%
      beforeStageTasks:
        - type: Approval