apiVersion: v1
kind: Namespace
metadata:
 name: guestbook
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-hub-manifests
  namespace: guestbook
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: project-gitops
  source:
    path: applications/simple-guestbook
    repoURL: https://github.com/ryanzhang-oss/fleet-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10
    syncOptions:
    - PruneLast=true
    - PrunePropagationPolicy=foreground
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true